### ISSUE TITLE
Error while trying to use this

### ISSUE THREAD

**Issue by samihadouaj** [AlexToumayan/Chat-GPT-Flashcards-To-Anki-Converter#1]
Hello,
I tried to run this script and I am getting the following error:

![image](https://user-images.githubusercontent.com/35850206/233150768-271a2592-6db5-4f68-a5c1-50be37d229fd.png)

Could you fix that pleaase?

**Comment by AlexToumayan** [comment]
Hi have you tried running the newest .py file? Please lmk if youre still running an error. That's an odd error as the parse function and other functions work locally for other users. Are you running windows or mac? I want to see if perhaps the new file should fix it.

**Comment by johnnyaber** [comment]
I have the same issue. Running windows here and python 3.1.

**Comment by AlexToumayan** [comment]
> I have the same issue. Running windows here and python 3.1.

Hello hope all is well! This program requires Python 3.6 or later. I attached in the read me file detailed instructions for installation. Please let me know if you have any other questions!
