### ISSUE TITLE
OS Ventura 13.0.1 Python 3.11.4

### ISSUE THREAD

**Issue by zet56fa** [AlexToumayan/Chat-GPT-Flashcards-To-Anki-Converter#3]
Hey, I followed your instruction but got stuck at the req command. Terminal gives me the following error:

iiiChat-GPT-Flashcards-To-Anki-Converter % pip install -r requirements.txt
Collecting genanki (from -r requirements.txt (line 1))
  Downloading genanki-0.13.0-py3-none-any.whl (13 kB)
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

https://pastebin.com/R3Ejn1k0.

I googled a bit and tired some troubleshooting but, I have no clue about python as a med stud, so it was not successful.

You can see my terminal and troubleshooting in my pastern, maybe you have an idea. Would you suggest I try it in a Windows env again ?.

**Comment by zet56fa** [comment]
I searched more and could install Tkinter over brew install python-tk. I reinstalled python and Tkinter over brew.
And checked the version.

python-tk@3.11 3.11.4 is already installed and up-to-date.   

But still the same Error, I guess it is a Mac problem right ? 
Collecting genanki (from -r requirements.txt (line 1))
  Using cached genanki-0.13.0-py3-none-any.whl (13 kB)
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

**Comment by AlexToumayan** [comment]
Hi thank you for the issue request I am happy to help! I realized some users are having some issues having tkinter in the requirements package as it usually comes with python already. However, some local machines have older versions or for some reason dont have it at all. 
Here's what you can do to fix the error:

Remove tkinter from requirements.txt(I've done this on the git but if you don't want to reinstall just pop open vscode and change the line):
Open the requirements.txt file and remove the line that has tkinter. Save the file and then try running the pip install -r requirements.txt command again. This should bypass the tkinter error. 

Ensure that tkinter is working:
After you have installed all the other packages, you can verify that tkinter is installed correctly by running the following command in the terminal:

python -m tkinter
**for some it can be python3 -m tkinter


Now if its still not working: 
I'm assuming at this point you've correctly installed Tkinter using Homebrew with brew install python-tk. However, it's essential to ensure the python or python3 command you use aligns with the version installed by Homebrew.
You can check this by typing which python3. If the output points to /usr/local/bin/python3 or similar (indicating a Homebrew path), it's correct. If it points to /usr/bin/python3, it's using the system version, which may not have the packages you installed via Homebrew.

If you encounter any other errors after trying these steps, let me know, and I'll be happy to help further!
