### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by BigAbz04** [AlexToumayan/Chat-GPT-Flashcards-To-Anki-Converter#5]
Hi.

I am running into an error while trying to install this.

I am a med student with very minimal computer knowledge.

This is what I get when I try to follow the instructions.

C:\Users\abhis\OneDrive\Documents\GitHub\Chat-GPT-Flashcards-To-Anki-Converter>pip install -r requirements.txt
Collecting genanki (from -r requirements.txt (line 1))
  Downloading genanki-0.13.0-py3-none-any.whl (13 kB)
ERROR: Could not find a version that satisfies the requirement re (from versions: none)
ERROR: No matching distribution found for re

Any help would be greatly appreciated.

Thank you!

**Comment by semarainc** [comment]
i think 're' in this case is builtin python library so you don't need to install it from pip
i suggest to remove 're' from requirements.txt then re run command "pip install -r requirements.txt"

**Comment by wizzardx** [comment]
There's a lot of python builtins there, I think the requirements.txt should be closer to this:

```
genanki
Pillow
markdown2
latex2mathml
pydub
```

**Comment by AlexToumayan** [comment]
Hi BigAbz04 I hope youre doing well. I wrote this script when I was still generally novice at programming. I fixed the issues and you shouldnt be having any errors from this point forward i also updated the readme file for clearer instructions I hope this helped!
